
data:
  #name: cora
  #name: pubmed
  #name: citeseer
  #name: news20
  #name: dblp4k-conf
  #name: dblp4k-paper
  #name: coauthorship_dblp
  #name: imdb4k
  name: dblp4k-term
  #name: cooking200

  num_train: 20
  num_val: 100
  ft_noise_level: 0.0
  self_loop: True
  random_split: True
model: 
  #name: gcn
  #name: gat 
  #name: hgnn
  #name: hgnnp
  name: kerhgnn
  #name: unignn
  #name: unigat
  #name: hnhn
  p_min: -0.5
  p_max: 2  
  hid: 32
  num_layer: 2
  kernel_type: mean
  mu: 1
optim:
  lr: 0.1
  lr_p: 0.003
wd: ${hydra:runtime.cwd}
data_marker: ${data.name}__${data.num_train}-${data.num_val}__noise-${data.ft_noise_level}
model_marker: ${model.name}-${model.p_min}-${model.p_max}
task: ${data_marker}__${model_marker}
res_path: ${wd}/cache/trans/${task}

hydra:
  run:
    dir: ${res_path}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: ${res_path}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}